title: Learning Pages wtih Jekyll
author: sswrighton
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  quick brown fox jumps over the lazy dog. quick brown fox jumps over the lazy dog. 
  quick brown fox jumps over the lazy dog.

# social links
twitter_username: kidananubix
github_username:  sswrighton

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
